version: '3.8'
services:
  database:
    image: postgres:16.2
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=essay_ace
    volumes:
      - ./data/postgres-data:/var/lib/postgresql/data
    expose:
      - "5432"
    ports:
      - "5432:5432"
  backend:
    image: ducminhdev/essay_ace:latest
    expose:
      - "5000"
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    env_file:
      - environments/backend.env
    command: bash -c "python main.py"
    depends_on:
      - database
  frontend:
    image: ducminhdev/essay_ace_fe:latest
    expose:
      - "3000"
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: ["npm", "run", "dev"]
